baseURL = "/"
title = "Matrix Specification"

# Prepends absolute URLs with the baseURL. Useful when hosting on non-root
# paths, such as /unstable.
canonifyURLs = true

enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]

disableKinds = ["taxonomy", "taxonomyTerm"]

[languages]
[languages.en]
title = "Matrix Specification"
description = "Home of the Matrix specification for decentralised communication"
languageName ="English"
# Weight used for sorting.
weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Enables us to render raw HTML
      unsafe = true
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      style = "tango"

# Everything below this are Site Params

[params]
copyright = "The Matrix.org Foundation CIC"
privacy_policy = "https://matrix.org/legal/privacy-notice"

[params.version]
# must be one of "unstable", "current", "historical"
# this is used to decide whether to show a banner pointing to the current release
status = "unstable"
# A URL pointing to the latest, stable release of the spec. To be shown in the unstable version warning banner.
current_version_url = "https://spec.matrix.org/latest"
# The following is used when status = "stable", and is displayed in various UI elements on a released version
# of the spec. CI will set these values here automatically when a release git tag (i.e `v1.5`) is created.
#major = "1"
#minor = "2"
#release_date = "February 02, 2022"

# User interface configuration
[params.ui]
# Set to true to disable the About link in the site footer
footer_about_disable = false
# Collapse HTTP API and event <details> elements
rendered_data_collapsed = false

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
# [[params.links.user]]
# 	name = "User mailing list"
# 	url = "https://example.org/mail"
# 	icon = "fa fa-envelope"
#         desc = "Discussion and help from your fellow users"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/matrix-org"
	icon = "fab fa-github"
  desc = "Matrix on GitHub"
[[params.links.developer]]
	name = "GitLab"
	url = "https://gitlab.matrix.org/matrix-org"
	icon = "fab fa-gitlab"
  desc = "Matrix on GitLab"
[[params.links.developer]]
	name = "YouTube"
	url = "https://www.youtube.com/channel/UCVFkW-chclhuyYRbmmfwt6w"
	icon = "fab fa-youtube"
  desc = "Matrix YouTube channel"
[[params.links.developer]]
	name = "Twitter"
	url = "https://twitter.com/matrixdotorg"
	icon = "fab fa-twitter"
  desc = "Matrix on Twitter"
