[ tool.gilesbot ]

  [ tool.gilesbot.circleci_artifacts.docs ]
    url = "public/index.html"
    message = "Click details to preview the HTML documentation."

  [ tool.gilesbot.circleci_artifacts.swagger ]
    url = "client-server/index.html"
    message = "Click to preview the swagger build."
