[tool.towncrier]
    version = "unused"
    filename = "../rendered.md"
    issue_format = "[#{issue}](https://github.com/matrix-org/matrix-doc/issues/{issue})"
    title_format = "### {name}"  # Matches rendered spec, even if awkward
    underlines = "   "  # 3 spaces intentionally to hide RST headings

    # Note: The names below have the <strong> tag built-in so the rendered spec *and* the generated
    # changelog can benefit from sane headings.

    [[tool.towncrier.type]]
        directory = "breaking"
        name = "<strong>Breaking Changes</strong>"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "deprecation"
        name = "<strong>Deprecations</strong>"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "new"
        name = "<strong>New Endpoints</strong>"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "removal"
        name = "<strong>Removed Endpoints</strong>"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "feature"
        name = "<strong>Backwards Compatible Changes</strong>"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "clarification"
        name = "<strong>Spec Clarifications</strong>"
        showcontent = true
