steps:
  - label: ":books: Build the legacy spec"
    command:
      # Install the python dependencies necessary to build the spec
      - python3 -m venv env && . env/bin/activate
      - pip install -r scripts/requirements.txt
      # Build the spec
      - scripts/generate-matrix-org-assets
    artifact_paths:
      - assets.tar.gz
    plugins:
      - docker#v3.7.0:
          image: python:3.9

  - label: "rebuild matrix.org"
    trigger: "matrix-dot-org"
    async: true
    branches: "master"

  - label: ":books: Build the spec"
    command:
      # Install package dependencies
      - apk add nodejs npm git hugo
      # Install the node dependencies necessary to build the spec
      - npm i
      # Pull all git submodules, required for the hugo theme
      - git submodule update --init --recursive
      # Pull current proposal information
      - npm run get-proposals
      # Build the spec, will build to './spec'
      - hugo -d "spec"
      # Compress the result and make it available as an artifact
      - tar -czf spec.tar.gz spec
    artifact_paths:
      - spec.tar.gz
    plugins:
      - docker#v3.7.0:
          image: alpine