# Copyright 2017 Michael Telatynski <7t3chguy@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
swagger: '2.0'
info:
  title: "Matrix Client-Server Room Listing API"
  version: "1.0.0"
host: localhost:8008
schemes:
  - https
  - http
basePath: /_matrix/client/%CLIENT_MAJOR_VERSION%
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  $ref: definitions/security.yaml
paths:
  "/joined_rooms":
    get:
      summary: Lists the user's current rooms.
      description: |-
        This API returns a list of the user's current rooms.
      operationId: getJoinedRooms
      security:
        - accessToken: []
      responses:
        200:
          description: A list of the rooms the user is in.
          schema:
            type: object
            required: ["joined_rooms"]
            properties:
              joined_rooms:
                type: array
                description: |-
                  The ID of each room in which the user has ``joined`` membership.
                items:
                  type: string
          examples:
            application/json: {
                "joined_rooms": [
                  "!foo:example.com"
                ]
              }
      tags:
        - Room membership
