#!/bin/sh
#
# generate a tarball of assets suitable for the matrix.org site

set -e

cd `dirname $0`/..

mkdir -p assets

# and the swagger
./scripts/dump-swagger.py -o assets/spec/client_server/api.json

# create a tarball of the assets.
tar -czf assets.tar.gz assets
