#!/bin/sh
#
# generate a tarball of assets suitable for the matrix.org site

set -e

cd `dirname $0`/..

mkdir -p assets

# generate specification/proposals.rst
./scripts/proposals.py

# generate the spec docs
./scripts/gendoc.py -d assets/spec

# and the swagger
./scripts/dump-swagger.py -o assets/spec/client_server/unstable.json

# create a tarball of the assets. Exclude the spec index for now, as
# we want to leave it pointing at the release versions of the specs.
# (XXX: how to maintain this?)
tar -czf assets.tar.gz --exclude="assets/spec/index.html" assets
