swagger: '2.0'
info:
  title: "Matrix Client-Server v1 state event send API"
  version: "1.0.0"
host: localhost:8008
schemes:
  - https
  - http
basePath: /_matrix/client/api/v1
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  accessToken:
    type: apiKey
    description: The user_id or application service access_token
    name: access_token
    in: query
paths:
  "/rooms/{roomId}/state/{eventType}/{stateKey}":
    put:
      summary: Send a message event to the given room.
      description: |
        State events can be sent using this endpoint.  These events will be
        overwritten if ``<room id>``, ``<event type>`` and ``<state key>`` all
        match.  If the state event has no ``state_key``, it can be omitted from
        the path. These requests **cannot use transaction IDs** like other
        ``PUT`` paths because they cannot be differentiated from the
        ``state_key``. Furthermore, ``POST`` is unsupported on state paths.

        The body of the request should be the content object of the event; the
        fields in this object will vary depending on the type of event. See
        `Room Events`_ for the ``m.`` event specification.
      security:
        - accessToken: []
      parameters:
        - in: path
          type: string
          name: roomId
          description: The room to set the state in
          required: true
          x-example: "!636q39766251:example.com"
        - in: path
          type: string
          name: eventType
          description: The type of event to send.
          required: true
          x-example: "m.room.name"
        - in: path
          type: string
          name: stateKey
          description: The state_key for the state to send. Defaults to the empty string.
          required: true
          x-example: ""
        - in: body
          name: body
          schema:
            type: object
            example: |-
              {
                  "name": "New name for the room"
              }
      responses:
        200:
          description: "An ID for the sent event."
          examples:
            application/json: |-
              {
                  "event_id": "YUwRidLecu"
              }
          schema:
            type: object
            properties:
              event_id:
                type: string
                description: |-
                  A unique identifier for the event.
